In [17]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root / "scripts"))

from event_utils import (
    load_events,
    compute_surprise,
    upcoming_events,
    biggest_surprises,
    reaction_by_asset,
    top_macro_shocks,
    inflation_shock_indicator,
    classify_surprise,
    reaction_consistency,
    event_snapshot,
)

In [18]:
events = load_events()
events = compute_surprise(events)

events.head()

,date,time,country,event,category,previous,forecast,actual,asset,move,market_reaction,notes,surprise
0,2026-03-10,14:30,US,CPI,inflation,3.1,3.2,3.4,UST2Y,0.10,yields up after hotter CPI,front-end reprices higher rates,0.2
1,2026-03-10,14:30,US,CPI,inflation,3.1,3.2,3.4,UST10Y,0.07,yields up after hotter CPI,long-end follows inflation risk,0.2
2,2026-03-10,14:30,US,CPI,inflation,3.1,3.2,3.4,DXY,0.45,dollar strengthens,higher rate expectations support USD,0.2
3,2026-03-10,14:30,US,CPI,inflation,3.1,3.2,3.4,SPX,-0.90,equities fall,valuation pressure from higher yields,0.2
4,2026-03-10,14:30,US,CPI,inflation,3.1,3.2,3.4,GOLD,0.30,gold slightly higher,safe-haven demand offsets yields,0.2

In [19]:
biggest_surprises(events)

,date,time,country,event,category,previous,forecast,actual,asset,move,market_reaction,notes,surprise,abs_surprise
5,2026-03-12,13:30,US,NFP,labour,210.0,190.0,250.0,UST2Y,0.08,yields rise,strong labor supports hawkish Fed,60.0,60.0
6,2026-03-12,13:30,US,NFP,labour,210.0,190.0,250.0,DXY,0.35,dollar up,strong macro data,60.0,60.0
7,2026-03-12,13:30,US,NFP,labour,210.0,190.0,250.0,SPX,0.40,equities up,growth optimism dominates,60.0,60.0
8,2026-03-12,13:30,US,NFP,labour,210.0,190.0,250.0,GOLD,-0.50,gold falls,real yields rise,60.0,60.0
14,2026-03-16,03:00,CN,Industrial Production,growth,5.2,5.0,4.6,OIL,-1.20,oil drops,weaker demand outlook,-0.4,0.4

In [20]:
reaction_by_asset(events, "UST10Y")

          date              event  surprise  move
1   2026-03-10                CPI       0.2  0.07
10  2026-03-14  ECB Rate Decision       0.0  0.02

In [21]:
reaction_by_asset(events, "DXY")

          date          event  surprise  move
2   2026-03-10            CPI       0.2  0.45
6   2026-03-12            NFP      60.0  0.35
19  2026-03-19  FOMC Decision       0.0  0.60

In [22]:
reaction_by_asset(events, "SPX")

          date                  event  surprise  move
3   2026-03-10                    CPI       0.2  -0.9
7   2026-03-12                    NFP      60.0   0.4
11  2026-03-14      ECB Rate Decision       0.0  -0.3
13  2026-03-16  Industrial Production      -0.4  -0.2
20  2026-03-19          FOMC Decision       0.0  -1.1

In [23]:
top_macro_shocks(events)

,date,country,event,category,surprise,notes,abs_surprise
1,2026-03-12,US,NFP,labour,60.0,strong labor supports hawkish Fed,60.0
3,2026-03-16,CN,Industrial Production,growth,-0.4,growth disappointment,0.4
4,2026-03-18,UK,CPI,inflation,-0.3,softer inflation,0.3

In [24]:
inflation_shock_indicator(events)

'Inflation running HOT'

In [25]:
events_labeled = classify_surprise(events)

events_labeled[["date", "event", "asset", "surprise", "surprise_label"]]

          date                  event    asset  surprise surprise_label
0   2026-03-10                    CPI    UST2Y       0.2       moderate
1   2026-03-10                    CPI   UST10Y       0.2       moderate
2   2026-03-10                    CPI      DXY       0.2       moderate
3   2026-03-10                    CPI      SPX       0.2       moderate
4   2026-03-10                    CPI     GOLD       0.2       moderate
5   2026-03-12                    NFP    UST2Y      60.0     very large
6   2026-03-12                    NFP      DXY      60.0     very large
7   2026-03-12                    NFP      SPX      60.0     very large
8   2026-03-12                    NFP     GOLD      60.0     very large
9   2026-03-14      ECB Rate Decision   EURUSD       0.0           none
10  2026-03-14      ECB Rate Decision   UST10Y       0.0           none
11  2026-03-14      ECB Rate Decision      SPX       0.0           none
12  2026-03-16  Industrial Production   USDCNH      -0.4     very large
13  2026-03-16  Industrial Production      SPX      -0.4     very large
14  2026-03-16  Industrial Production      OIL      -0.4     very large
15  2026-03-18                    CPI  GILT10Y      -0.3       moderate
16  2026-03-18                    CPI   GBPUSD      -0.3       moderate
17  2026-03-18                    CPI     FTSE      -0.3       moderate
18  2026-03-19          FOMC Decision    UST2Y       0.0           none
19  2026-03-19          FOMC Decision      DXY       0.0           none
20  2026-03-19          FOMC Decision      SPX       0.0           none
21  2026-03-19          FOMC Decision     GOLD       0.0           none

In [26]:
events_checked = reaction_consistency(events)

events_checked

,date,event,asset,surprise,move,expected_direction,actual_direction,reaction_match
0,2026-03-10,CPI,UST2Y,0.2,0.10,up,up,True
1,2026-03-10,CPI,UST10Y,0.2,0.07,up,up,True
2,2026-03-10,CPI,DXY,0.2,0.45,up,up,True
3,2026-03-10,CPI,SPX,0.2,-0.90,down,down,True
4,2026-03-10,CPI,GOLD,0.2,0.30,unclear,up,False
5,2026-03-12,NFP,UST2Y,60.0,0.08,unclear,up,False
6,2026-03-12,NFP,DXY,60.0,0.35,unclear,up,False
7,2026-03-12,NFP,SPX,60.0,0.40,unclear,up,False
8,2026-03-12,NFP,GOLD,60.0,-0.50,unclear,down,False
9,2026-03-14,ECB Rate Decision,EURUSD,0.0,0.20,unclear,up,False
10,2026-03-14,ECB Rate Decision,UST10Y,0.0,0.02,unclear,up,False
11,2026-03-14,ECB Rate Decision,SPX,0.0,-0.30,unclear,down,False
12,2026-03-16,Industrial Production,USDCNH,-0.4,0.25,unclear,up,False
13,2026-03-16,Industrial Production,SPX,-0.4,-0.20,unclear,down,False
14,2026-03-16,Industrial Production,OIL,-0.4,-1.20,unclear,down,False
15,2026-03-18,CPI,GILT10Y,-0.3,-0.12,unclear,down,False
16,2026-03-18,CPI,GBPUSD,-0.3,-0.40,unclear,down,False
17,2026-03-18,CPI,FTSE,-0.3,0.50,unclear,up,False
18,2026-03-19,FOMC Decision,UST2Y,0.0,0.15,unclear,up,False
19,2026-03-19,FOMC Decision,DXY,0.0,0.60,unclear,up,False
20,2026-03-19,FOMC Decision,SPX,0.0,-1.10,unclear,down,False
21,2026-03-19,FOMC Decision,GOLD,0.0,-0.80,unclear,down,False

In [27]:
event_snapshot(events, "CPI", "2026-03-10")

,date,time,country,event,asset,move,market_reaction,notes,surprise
2,2026-03-10,14:30,US,CPI,DXY,0.45,dollar strengthens,higher rate expectations support USD,0.2
4,2026-03-10,14:30,US,CPI,GOLD,0.30,gold slightly higher,safe-haven demand offsets yields,0.2
3,2026-03-10,14:30,US,CPI,SPX,-0.90,equities fall,valuation pressure from higher yields,0.2
1,2026-03-10,14:30,US,CPI,UST10Y,0.07,yields up after hotter CPI,long-end follows inflation risk,0.2
0,2026-03-10,14:30,US,CPI,UST2Y,0.10,yields up after hotter CPI,front-end reprices higher rates,0.2